# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/sagernet/cors
%global goihead cors
%global goipath github.com/sagernet/%{goihead}
Version:  1.2.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
CORS net/http middleware for Go.}

%global golicenses      LICENSE
Name:           golang-github-sagernet-cors
Release:        %autorelease
Summary:        CORS net/http middleware for Go

License:        MIT
URL:            %{gourl}
%define stag %{?tag}%{?!tag:%commit}
Source: https://%{goipath}/archive/%{stag}/%{goihead}-%{stag}.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check

%endif
%endif

%gopkgfiles

%changelog
%autochangelog
